version: "3"

services:
  router:
    ####################
    image: "nginx:latest"
    container_name: nginx-router
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx-server
    ports:
      - "80:80"
  nexus:
    image: "sonatype/nexus3:latest"
    container_name: "local-docker-repo"
    ports: 
      - "8081:8081"
      - "8082:8082"
    restart: always
    volumes:
      - ./nexus-docker-repo/local-nexus-data:/nexus-data
  jenkins:
    image: "jenkins/jenkins" 
    container_name: "jenkins-server"
    ports: 
      - "8080:8080"
    volumes:
      - "./jenkins-server/jenkins_home:/var/jenkins_home"
        

